# Generated by Django 3.2.17 on 2023-02-16 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.ImageField(upload_to='comp')),
                ('date', models.DateField()),
                ('latitude', models.CharField(max_length=50)),
                ('altitude', models.CharField(max_length=50)),
                ('current_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptName', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=50)),
                ('contact_no', models.BigIntegerField()),
                ('email_id', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('post_office', models.CharField(max_length=50)),
                ('pin_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('post_office', models.CharField(max_length=50)),
                ('pin_code', models.IntegerField()),
                ('phone_number', models.BigIntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('email_id', models.CharField(max_length=50)),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qiuck_fix_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Reason', models.CharField(max_length=60)),
                ('complaintid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qiuck_fix_app.complaints')),
            ],
        ),
        migrations.CreateModel(
            name='officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('post_office', models.CharField(max_length=50)),
                ('pin_code', models.IntegerField()),
                ('phone_number', models.BigIntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('email_id', models.CharField(max_length=50)),
                ('deptid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qiuck_fix_app.dept')),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qiuck_fix_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=80)),
                ('date', models.DateField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qiuck_fix_app.users')),
            ],
        ),
        migrations.AddField(
            model_name='dept',
            name='lid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qiuck_fix_app.login'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='depid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qiuck_fix_app.dept'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qiuck_fix_app.users'),
        ),
        migrations.CreateModel(
            name='assignedcomplaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('complaintid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qiuck_fix_app.complaints')),
                ('officerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qiuck_fix_app.officer')),
            ],
        ),
    ]
